ci: bump install-nix-action to v22 to get upstream `macos` install fix (#81)
closes #80.

This PR gets the fix mentioned
[here](https://github.com/cachix/install-nix-action/issues/183#issuecomment-1595162172).
Fixes the CI so that following error is not blocking our macos runners in installing step:

```console
Could not set environment: 150: Operation not permitted while System Integrity Protection is engaged
  Error: Process completed with exit code 150.
```